#!/usr/bin/ env bash
#Write a Bash script that displays the content of the file /etc/passwd.
#Your script should only display:
#username
#user id
#Home directory path for the user
while IFS= read -r contents
do
	echo "$contents" | cut -f 1,3,6 -d ":"
done > "/etc/passwd"
