#!/usr/bin/env bash
#displays the content of the file /etc/passwd with story

while IFS=':' read -r username password uid gid info home shell; do
  echo "The user $username is part of the $gid gang."\
  echo "lives in $home and rides $shell."\
  echo "$uid's place is protected by the passcode $password,"\
  echo "more info about the user here: $info"	
done < "/etc/passwd"
