#!/usr/bin/env bash
#A Bash script that diplays Best School 10 times, but for the 9th it says Best School and then Hi on a new line
count=0
while [$count -lt 10]
do
if [$count -eq 9]
then
echo "Hi"
fi
echo "Best School"
((count++))
done
